[package]
name = "s2-utils"
version = "0.2.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
s2-utils-derive = { path = "crates/s2-utils-derive" }
dotenv = "0.13"
reqwest = "0.9"