[package]
name = "s2-utils"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2021"

[dependencies]
s2-utils-derive = { path = "crates/s2-utils-derive" }
dotenv = "0.15.0"
reqwest = "0.11.14"