[package]
name = "s2-utils-derive"
version = "0.2.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "0.12.10", features = ["full"] }
quote = "0.4.2"
proc-macro2 = { version = "0.2" }

[lib]
proc-macro = true
